# Generated by Django 5.1.2 on 2024-12-13 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_alter_student_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.attendanceclass'),
        ),
    ]
